import os

# Observation windows in hours for different action types
OUTCOME_RESTOCK_WINDOW_HOURS = int(os.getenv("OUTCOME_RESTOCK_WINDOW_HOURS", 24))
OUTCOME_PROMOTION_WINDOW_HOURS = int(os.getenv("OUTCOME_PROMOTION_WINDOW_HOURS", 24))
OUTCOME_WINBACK_WINDOW_HOURS = int(os.getenv("OUTCOME_WINBACK_WINDOW_HOURS", 72))
OUTCOME_RETENTION_WINDOW_HOURS = int(os.getenv("OUTCOME_RETENTION_WINDOW_HOURS", 72))
OUTCOME_CROSS_SELL_WINDOW_HOURS = int(os.getenv("OUTCOME_CROSS_SELL_WINDOW_HOURS", 48))
OUTCOME_DEFAULT_WINDOW_HOURS = int(os.getenv("OUTCOME_DEFAULT_WINDOW_HOURS", 24))

# Minimum transactions required to avoid INSUFFICIENT_DATA
MIN_TRANSACTIONS_FOR_MEASUREMENT = int(os.getenv("MIN_TRANSACTIONS_FOR_MEASUREMENT", 1))

# Action Type to Default Window Mapping
ACTION_WINDOW_MAP = {
    "REORDER": OUTCOME_RESTOCK_WINDOW_HOURS,
    "RESTOCK_PRODUCT": OUTCOME_RESTOCK_WINDOW_HOURS,
    "PROMOTION": OUTCOME_PROMOTION_WINDOW_HOURS,
    "SEND_OFFER": OUTCOME_PROMOTION_WINDOW_HOURS,
    "RUN_PROMOTION": OUTCOME_PROMOTION_WINDOW_HOURS,
    "WINBACK": OUTCOME_WINBACK_WINDOW_HOURS,
    "CUSTOMER_WINBACK": OUTCOME_WINBACK_WINDOW_HOURS,
    "CUSTOMER_RETENTION": OUTCOME_RETENTION_WINDOW_HOURS,
    "CROSS_SELL": OUTCOME_CROSS_SELL_WINDOW_HOURS,
    "CREATE_BUNDLE": OUTCOME_CROSS_SELL_WINDOW_HOURS,
    "MONITOR_TREND": OUTCOME_DEFAULT_WINDOW_HOURS,
    "FINANCIAL_PRODUCT": OUTCOME_DEFAULT_WINDOW_HOURS,
}

def get_observation_window_hours(action_type: str) -> int:
    return ACTION_WINDOW_MAP.get(str(action_type).upper(), OUTCOME_DEFAULT_WINDOW_HOURS)
