import os
from enum import Enum


class FeedbackType(str, Enum):
    MERCHANT_APPROVED = "MERCHANT_APPROVED"
    MERCHANT_REJECTED = "MERCHANT_REJECTED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    ACTION_FAILED = "ACTION_FAILED"
    POSITIVE_OUTCOME = "POSITIVE_OUTCOME"
    NEUTRAL_OUTCOME = "NEUTRAL_OUTCOME"
    NEGATIVE_OUTCOME = "NEGATIVE_OUTCOME"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    RECOMMENDATION_EXPIRED = "RECOMMENDATION_EXPIRED"
    EXPIRED = "EXPIRED"
    MERCHANT_IGNORED = "MERCHANT_IGNORED"
    MERCHANT_RATING = "MERCHANT_RATING"
    MERCHANT_FEEDBACK_POSITIVE = "MERCHANT_FEEDBACK_POSITIVE"
    MERCHANT_FEEDBACK_NEGATIVE = "MERCHANT_FEEDBACK_NEGATIVE"
    HIGH_CONFIDENCE_SUCCESS = "HIGH_CONFIDENCE_SUCCESS"
    LOW_CONFIDENCE_SUCCESS = "LOW_CONFIDENCE_SUCCESS"
    HIGH_CONFIDENCE_FAILURE = "HIGH_CONFIDENCE_FAILURE"
    LOW_CONFIDENCE_FAILURE = "LOW_CONFIDENCE_FAILURE"


class RecommendationEffectiveness(str, Enum):
    SUCCESSFUL = "SUCCESSFUL"
    PARTIALLY_SUCCESSFUL = "PARTIALLY_SUCCESSFUL"
    UNSUCCESSFUL = "UNSUCCESSFUL"
    NOT_MEASURED = "NOT_MEASURED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


# Decision Engine Feedback Adjustment Weights
FEEDBACK_WEIGHT = float(os.getenv("FEEDBACK_WEIGHT", 0.10))
MAX_FEEDBACK_ADJUSTMENT = float(os.getenv("MAX_FEEDBACK_ADJUSTMENT", 0.10))
FEEDBACK_CACHE_TTL_SECONDS = int(os.getenv("FEEDBACK_CACHE_TTL_SECONDS", 3600))
